//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointLess2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlot
    {
        public long Id { get; set; }
        public byte DaysOfWeek { get; set; }
        public System.TimeSpan TimeOfDay { get; set; }
        public int LengthMinutes { get; set; }
        public int ScheduleID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
